services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
    env_file:
      - .env
    networks:
      - festival-backend
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - festival_db_data:/var/lib/postgresql/data
    container_name: festival_postgres_db

  backend:
    build: .
    restart: always
    env_file:
      - .env
    networks:
      - festival-backend
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      db:
        condition: service_healthy
    container_name: festival_backend

volumes:
  festival_db_data:
    name: festival_db_data

networks:
  festival-backend:
    name: festival-backend
